User input
raven-os/feathers-deprecated pull request #11
Opened 2018-05-27 15:36 UTC by riamon-v

2018-05-29 16:59 UTC, Gaspard-- requested changes
Overall the code isn't great, but isn't bad either. I'd be ok with merging this, but it could be quite a bit cleaner and it would be interesting to investigate if a singleton is really necessary.

2018-05-29 16:59 UTC, Gaspard-- commented on .gitignore
> +#*#
I'll let @Arignir explain why this shouldn't be your approach.

2018-05-29 16:59 UTC, Gaspard-- commented on source/main.cpp
> +
All of lines above dont look clean. Maybe should be behind an init method or in a constructor? Overall I don't see why a singleton is necessary.

2018-05-29 16:59 UTC, Gaspard-- commented on source/main.cpp
> +	UserInput::createWindow();
create usually returns a object or something like that. This seems counter intuitive.

2018-05-29 16:59 UTC, Gaspard-- commented on source/main.cpp
> +	eglTerminate(UserInput::get().egl_display);
This screams of missing RAII.

2018-05-29 16:59 UTC, Gaspard-- commented on source/user-input/Listeners.cpp
> +
Empty destructor is rarely a good choice. `default` it or something.

2018-05-29 16:59 UTC, Gaspard-- commented on source/user-input/UserInput.cpp
> +																							UserInput::instance.compositor);
This indentation is unreadable.

2018-05-29 16:59 UTC, Gaspard-- commented on source/user-input/listeners/KeyboardListener.cpp
> +void KeyboardListener::keyboard_leave (void *data, struct wl_keyboard *keyboard, uint32_t serial, struct wl_surface *surface) {
You seem to not be compiling with `-Wall`. Unused params shouldn't be named.

2018-05-29 16:59 UTC, Gaspard-- commented on source/user-input/listeners/KeyboardListener.cpp
> +void KeyboardListener::keyboard_leave (void *data, struct wl_keyboard *keyboard, uint32_t serial, struct wl_surface *surface) {
This concerns a bunch of functions. I won't list them.

2018-05-29 16:59 UTC, Gaspard-- commented on source/user-input/listeners/RegistryListener.cpp
> +  static struct wl_registry_listener registry_listener =
What about `constexpr` ?

2018-05-29 16:59 UTC, Gaspard-- commented on source/user-input/listeners/RegistryListener.cpp
> +	if (!strcmp(interface,"wl_compositor")) {
Please use `std::strcmp`.

2018-05-29 16:59 UTC, Gaspard-- commented on include/user-input/UserInput.hpp
> +#include <string.h>
use `<cstring>` instead.

2018-05-29 16:59 UTC, Gaspard-- commented on include/user-input/UserInput.hpp
> +#include <stdio.h>
use `<cstdio>` instead.

2018-05-29 17:03 UTC, Arignir commented on .gitignore
> +#*#
At least, these ones i don't care, they are shared across so many editors that it's fine.

But in other cases, try to put personal files in `/.git/info/exclude` and not `/.gitignore`

2018-05-29 17:04 UTC, Gaspard-- commented on .gitignore
> +#*#
Well a little lower, there's also a random directory (I know, `build/` is not random, but only to people who name it "build") which definitely shouldn't be here.

2018-06-03 19:45 UTC, davidzeng8 commented
Seems like nobody is working on this PR, maybe we should close it ?

2018-06-03 19:46 UTC, Gaspard-- commented
Yes

2018-06-03 19:46 UTC, closed without merging