Kernel display
raven-os/feathers-deprecated pull request #13
Opened 2018-06-03 22:35 UTC by davidzeng8

2018-06-04 06:55 UTC, riamon-v commented on .gitignore
>  # Prerequisites
You have to remove this from gitignore

2018-06-04 07:24 UTC, Zeng-Zer commented on .gitignore
>  # Prerequisites
Why ? :O

2018-06-04 19:54 UTC, Gaspard-- requested changes
The good news is, it seems the difference between this and having a swapchain seem minimal, so it should be possible to abstract both away.
I think your PR needs a slight cleanup (it shouldn't take long), and I'm happy you're advancing so quickly.

2018-06-04 19:54 UTC, Gaspard-- commented on .gitignore
>  # Prerequisites
It's not something general, it's specific to your build (you chose the `build` directory when running cmake) so it should go in `.git/info/exclude`

2018-06-04 19:54 UTC, Gaspard-- commented on CMakeLists.txt
> +find_package(OpenGL REQUIRED)
You need both EGL and OpenGL ? I'm a little surprised...

2018-06-04 19:54 UTC, Gaspard-- commented on include/Exception.hpp
> +class Exception : public std::exception {
Difference with `std::runtime_error`? If you only need a new type inherit from that class instead and abuse the `using` keyword please.

2018-06-04 19:54 UTC, Gaspard-- commented on include/Exception.hpp
> +  virtual ~Exception() throw() {}
Note: `throw()` shouldn't be used any more, use `noexcept` instead.

2018-06-04 19:54 UTC, Gaspard-- commented on include/modeset/ModeSetter.hpp
> +extern "C"
Why?

2018-06-04 19:54 UTC, Gaspard-- commented on source/main.cpp
> +  if (argc == 1)
Wasn't the check I was imagining, but eh :man_shrugging:

2018-06-04 19:54 UTC, Gaspard-- commented on source/main.cpp
> +	      usleep(100);
This is peculiar. I would expect swapping buffers to block.

2018-06-04 19:54 UTC, Gaspard-- commented on source/modeset/ModeSetter.cpp
> +  initGBM();
I like the idea of separating both. Could we go further and have a struct for each in the class with their own constructors?

2018-06-04 20:30 UTC, davidzeng8 commented on source/main.cpp
> +	      usleep(100);
What do you mean by swapping buffers to block ?

2018-06-04 20:35 UTC, davidzeng8 commented on include/Exception.hpp
> +class Exception : public std::exception {
https://stackoverflow.com/a/1569760 this post should answer your question

2018-06-04 20:48 UTC, davidzeng8 commented on CMakeLists.txt
> +find_package(OpenGL REQUIRED)
I only need opengl for the glClear() / glClearColor() call

2018-06-04 21:20 UTC, Gaspard-- commented on include/Exception.hpp
> +class Exception : public std::exception {
That was a rhetorical question.
If you want a string, inherit from `std::runtime_error`. One could argue that the standard provides `std::logic_error` too for semantics, but since we don't write defensive code, that second one should be useless. I could also be open to custom exceptions (inheriting or not from `std::exception`) in certain cases (such as for error codes and so on you want to inspect on the catch site). However, defining your own exception class with exactly the same interface as `std::runtime_error` is just poor practice: you're writing technically useless code (which means greater surface for bugs).

2018-06-05 09:06 UTC, davidzeng8 commented on include/Exception.hpp
> +class Exception : public std::exception {
I'm kind of used to java exceptions. I agree, custom exceptions might not be a good idea here, but they could be useful for specific error in other part of the program to prevent catching every error with `try/catch`

2018-06-05 10:03 UTC, Gaspard-- commented on source/main.cpp
> +	      usleep(100);
I meant `modeSetter.swapBuffers();` would somehow wait for a vertical blank. Maybe you need to set the swapinterbval or something like that. Otherwise we might end up with screen tiering.

2018-06-05 20:19 UTC, Gaspard-- commented on include/Exception.hpp
> +class Exception : public std::exception {
I just realised we've been missing our points all along: I wasn't speaking of the difference between `std::exception` and `std::runtime_error`, but between your class and `std::runtime_error`.
I'd replace `Exception` by `std::runtime_error` and implement `ModeSettingError` something like this:
```cpp
class ModeSettingError : public std::runtime_error
{
public:
  using std::runtime_error::runtime_error;
};
```
Or if modsetting returns specific errors (with nice error codes and so on):
```cpp
class ModeSettingError : public std::exception
{
  int error;
public:
  ModeSettingError(int error); // which would be implemented as a basic constructor
  int getError() const; // a simple getter to act depending on error code
  char const *what(); // would return the appropriate message depending on the error code.
  // Needed dynamic storage could be staticly allocated or something like that.
};
```
The second would allow for more fine grained error handling. But it may be overkill. Go for the first if you don't feel the second is that usefull, we can always replace the exception with a more detailed one later.

2018-06-05 21:11 UTC, Gaspard-- approved these changes

2018-06-05 21:12 UTC, Gaspard-- commented
LGTM, merging.

2018-06-05 21:12 UTC, merged