Added wayland server protocol
raven-os/feathers-deprecated pull request #17
Opened 2018-06-23 10:40 UTC by plean

- WaylandServerProtocol class
- AddSocket method
- AddProtocolLogger method

2018-06-23 10:47 UTC, Gaspard-- requested changes
Minor fix necessary.

2018-06-23 10:47 UTC, Gaspard-- commented on source/protocol/WaylandServerProtocol.cpp
> +{
Seems like `wlProtocolLogger` isn't initialised. Also I think you should be using member initialisation, like:
```cpp
WaylandServerProtocol()
: wlDisplay(...),
[...]
```

2018-06-23 11:38 UTC, Gaspard-- requested changes

2018-06-23 11:38 UTC, Gaspard-- commented on source/main.cpp
> +  (void)message;
prefer not naming the parameters.

2018-06-23 11:38 UTC, Gaspard-- commented on source/main.cpp
> +	  int socket_nb = atoi(argv[i] + 8);
You should be taking a socket name (not an actual socket) and pass that name to the wayland protocol so it creates the sockets.

2018-06-23 11:38 UTC, Gaspard-- commented on include/protocol/WaylandServerProtocol.hpp
> +#include <errno.h>
Prefer moving includes not needed by the `.hpp` in the proper `.cpp`s instead (such as `errno.h` and `string.h`but not `string`). This avoids pulling stuff into other peoples code, and also speeds up compilation (even if slightly, it will add up).

2018-06-23 11:39 UTC, Gaspard-- commented
Note, this PR concerns #16

2018-06-23 11:52 UTC, plean commented on source/main.cpp
> +	  int socket_nb = atoi(argv[i] + 8);
that's exactly what I did
```
              printf("AddSocket method with name '%s' was %s\n", argv[i + 1], serverProtocol.AddSocket(argv[i + 1]) ? "unsuccessful" : "successful");
```
argv[i + 1] correspond to the socket's name

2018-06-23 11:54 UTC, Gaspard-- commented on source/main.cpp
> +	  int socket_nb = atoi(argv[i] + 8);
ah, I misinterpreted the use of the `atoi`. Ok, works for me then.

2018-06-23 11:59 UTC, Gaspard-- reviewed
The rest of the main makes no sense now of course.
But for the moment you can concentrate on the moving forward.

2018-06-23 12:02 UTC, Gaspard-- commented
TODO:
- [ ] repair main (so that you can do more than test the protocol)
- [ ] add socket name parameter for the client (`display::WaylandSurface`)
- [ ] start investigating the rest of the protocol

2018-09-08 23:03 UTC, Gaspard-- commented
Clean-up main:
- [ ] protocol active in all back-ends
- [ ] `WindowTree` accessible from protocol

2018-09-09 15:47 UTC, riamon-v approved these changes
LGTM

2018-09-09 22:46 UTC, Gaspard-- commented
Ok, I'll merge and open appropriate issues then.

2018-09-09 22:49 UTC, Gaspard-- approved these changes

2018-09-09 22:50 UTC, merged