Added argument handling with getopts #36
raven-os/feathers-deprecated pull request #50
Opened 2018-09-25 17:38 UTC by plean

2018-09-25 17:39 UTC, Gaspard-- requested changes
I left some comments on the commit already, also please merge master.

2018-09-25 17:46 UTC, Gaspard-- commented on source/main.cpp
>  static void debug_server_protocol([[maybe_unused]]void *user_data,
Instead of using static to avoid linakge, you can use an anonymous namespace instead.

2018-09-25 17:47 UTC, Gaspard-- commented on source/main.cpp
> +      static const struct option long_options[] =
Said on commit: could be constexpr.

2018-09-25 17:47 UTC, Gaspard-- commented on source/main.cpp
> +      putchar('\n');
Should probably bail in this case (print usage or something like that)

2018-09-25 17:48 UTC, Gaspard-- commented on source/main.cpp
> +      putchar('\n');
And the maybe add error somewhere in the message so the user knows he screwed up

2018-09-25 19:25 UTC, Gaspard-- commented on source/main.cpp
> +  for (auto it = args.clientSocketsNames.begin(); it < args.clientSocketsNames.end(); it++)
Said on commit: You could use the traditional `for (auto const &str : args.clientSocketsNames)` instead

2018-09-25 21:21 UTC, plean commented on source/main.cpp
>  static void debug_server_protocol([[maybe_unused]]void *user_data,
That's not part of my code

2018-09-25 21:22 UTC, Gaspard-- commented on source/main.cpp
>  static void debug_server_protocol([[maybe_unused]]void *user_data,
True, I'll open a issue instead.

2018-09-25 21:22 UTC, Gaspard-- commented on source/main.cpp
> +static void help(std::string const &name)
This one's from your code though.

2018-09-25 21:24 UTC, Gaspard-- commented on include/Args.hpp
> +  Args(): socketName(""), mode(-1) {};
Instead of declaring a constructor it might be cleaner to just initialize the variables. The advantage being it's easier to read and that the default value is visible next to each member.

2018-09-25 21:25 UTC, Gaspard-- commented on source/main.cpp
> +static void help(std::string const &name)
Actually I think it's easier to address the problem separately.

2018-09-26 15:35 UTC, Gaspard-- commented
LGTM now, I'll do a quick grammar check.

2018-09-26 15:47 UTC, Gaspard-- requested changes
Minor grammar and writing style quibbles remaining.

2018-09-26 15:47 UTC, Gaspard-- commented on source/main.cpp
> +	 "\t-s, --socket\t\t weston socket name (default if not specify)\n\n"
specify -> specified

2018-09-26 15:47 UTC, Gaspard-- commented on source/main.cpp
> +            puts("Mode cannot be TTY and SubCompositor\n");
'cannot' is a little casual in this context
I'd put something like "Mode can't be *both* 'TTY' and 'sub-compositor'"

2018-09-26 15:47 UTC, Gaspard-- commented on source/main.cpp
> +            puts("Mode cannot be SubCompositor and TTY\n");
See above.

2018-09-26 15:47 UTC, Gaspard-- commented on source/main.cpp
> +            puts("Cannot set client-socket in non SubCompositor modes\n");
I'd reverse the sentence:
"'client-socket' may only be set in TTY mode"

2018-09-26 15:47 UTC, Gaspard-- commented on source/main.cpp
> +      printf("non-option ARGV-elements: ");
"ARGV-elements" may not make sens for a user
"argruments" would be fine instead.

2018-09-26 16:11 UTC, Gaspard-- approved these changes

2018-09-26 16:11 UTC, merged