Subcompositor (display and input), Kernel rendering, and basic rendering
raven-os/feathers-deprecated pull request #9
Opened 2018-05-26 11:23 UTC by Gaspard--

- adds FindWayland.cmake
- adds shaders
- updates display/

2018-06-05 21:40 UTC, Zeng-Zer requested changes

2018-06-05 21:40 UTC, davidzeng8 commented on include/display/WaylandAdapters.hpp
> +  const wl_pointer_listener *pointer_listener = new wl_pointer_listener
camelCase

2018-06-05 21:40 UTC, davidzeng8 commented on include/display/WaylandAdapters.hpp
> +  const wl_keyboard_listener *keyboard_listener = new wl_keyboard_listener
same

2018-06-05 21:40 UTC, davidzeng8 commented on include/display/WaylandAdapters.hpp
> +  const wl_seat_listener *seat_listener = new wl_seat_listener
same

2018-06-05 21:40 UTC, davidzeng8 commented on include/display/WaylandAdapters.hpp
> +  const wl_registry_listener *registry_listener = new wl_registry_listener
same

2018-06-05 21:40 UTC, davidzeng8 commented on include/display/WaylandAdapters.hpp
> +  const wl_shell_surface_listener *shell_surface_listener = new wl_shell_surface_listener
same

2018-06-05 21:40 UTC, davidzeng8 commented on include/display/WaylandSurface.hpp
> +    void shell_surface_ping(struct wl_shell_surface *shell_surface, uint32_t serial);
Also cameCase for these functions  / parameters

2018-06-05 21:40 UTC, davidzeng8 commented on include/listeners/KeyboardListener.hpp
> +  struct xkb_context *xkb_context;
camelCase

2018-06-05 21:40 UTC, davidzeng8 commented on include/listeners/KeyboardListener.hpp
> +    void keyboard_keymap(struct wl_keyboard *keyboard, uint32_t format, int32_t fd, uint32_t size);
same

2018-06-05 21:40 UTC, davidzeng8 commented on include/listeners/PointerListener.hpp
> +    void pointer_enter(struct wl_pointer *pointer, uint32_t serial, struct wl_surface *surface, wl_fixed_t surfX, wl_fixed_t surfY);
same

2018-06-05 21:40 UTC, davidzeng8 commented on include/listeners/SeatListener.hpp
> +  KeyboardListener *keyboard_listener;
same

2018-06-05 21:40 UTC, davidzeng8 commented on include/listeners/SeatListener.hpp
> +    void seat_capabilities(struct wl_seat *seat, uint32_t capabilities);
same

2018-06-05 21:40 UTC, davidzeng8 commented on source/display/WaylandSurface.cpp
> +    wl_shell_surface_pong (shell_surface, serial);
same as above

2018-06-05 21:40 UTC, davidzeng8 commented on source/display/WaylandSurface.cpp
> +  void WaylandSurface::shell_surface_ping (struct wl_shell_surface *shell_surface, uint32_t serial)
no whitespace between function name and parenthesis `f(()` vs `f ()`

2018-06-05 21:40 UTC, davidzeng8 commented on source/listeners/KeyboardListener.cpp
> +  char *keymap_string = static_cast<char *>(mmap(NULL, size, PROT_READ, MAP_SHARED, fd, 0));
camelCase and nullptr

2018-06-05 21:40 UTC, davidzeng8 commented on source/listeners/KeyboardListener.cpp
> +  xkb_state = xkb_state_new(keymap);
cameCase

2018-06-05 21:40 UTC, davidzeng8 commented on source/listeners/KeyboardListener.cpp
> +  printf("Entering the window\n");
`std::cout` instead of printf

2018-06-05 21:40 UTC, davidzeng8 commented on source/listeners/KeyboardListener.cpp
> +  printf("Leaving the window\n");
same as above

2018-06-05 21:40 UTC, davidzeng8 commented on source/listeners/KeyboardListener.cpp
> +    xkb_keysym_t keysym = xkb_state_key_get_one_sym(xkb_state, key + 8);
comment magic numbers :o ?

2018-06-05 21:40 UTC, davidzeng8 commented on source/listeners/KeyboardListener.cpp
> +void KeyboardListener::keyboard_modifiers (struct wl_keyboard *keyboard, uint32_t serial, uint32_t mods_depressed, uint32_t mods_latched, uint32_t mods_locked, uint32_t group)
whitespace between function and parenthesis
cameCase for parameters

2018-06-05 21:40 UTC, davidzeng8 commented on source/listeners/PointerListener.cpp
> +void PointerListener::pointer_enter(struct wl_pointer *pointer, uint32_t serial, struct wl_surface *surface, wl_fixed_t surface_x, wl_fixed_t surface_y)
not same parameter name as in hpp file :o ?

2018-06-05 21:40 UTC, davidzeng8 commented on source/display/WaylandSurface.cpp
> +    if (!wlCompositor) {
bracket under if

2018-06-05 21:40 UTC, davidzeng8 commented on source/display/WaylandSurface.cpp
> +      	if (!wlSurface) {
bracket misplaced

2018-06-05 21:40 UTC, davidzeng8 commented on source/display/WaylandSurface.cpp
> +  void WaylandSurface::registry_remove_object(struct wl_registry *registry, uint32_t name) {
same

2018-06-05 21:40 UTC, davidzeng8 commented on source/display/WaylandSurface.cpp
> +  void WaylandSurface::dispatch() {
same

2018-06-05 21:40 UTC, davidzeng8 commented on source/listeners/KeyboardListener.cpp
> +  : xkb_context(xkb_context_new (XKB_CONTEXT_NO_FLAGS)) {
bracket misplaced

2018-06-05 21:40 UTC, davidzeng8 commented on source/listeners/KeyboardListener.cpp
> +  if (state == WL_KEYBOARD_KEY_STATE_PRESSED) {
bracket misplaced

2018-06-05 21:40 UTC, davidzeng8 commented on source/listeners/KeyboardListener.cpp
> +    if (utf32) {
bracket misplaced

2018-06-05 21:40 UTC, davidzeng8 commented on source/listeners/KeyboardListener.cpp
> +bool KeyboardListener::getRunning() const {
bracket misplaced

2018-06-05 21:40 UTC, davidzeng8 commented on source/listeners/SeatListener.cpp
> +SeatListener::SeatListener() {
bracket misplaced

2018-06-05 21:40 UTC, davidzeng8 commented on source/listeners/SeatListener.cpp
> +void SeatListener::seat_capabilities(struct wl_seat *seat, uint32_t capabilities) {
bracket misplaced

2018-06-05 21:40 UTC, davidzeng8 commented on include/display/WaylandSurface.hpp
>      static std::vector<char const *> getRequiredExtensiosn()
typo Extensions

2018-06-05 23:16 UTC, Gaspard-- commented
Since I haven't taken care of `magma/DisplaySystem` yet, to test this branch you can apply this hacky patch:
```cpp
@@ -73,7 +73,7 @@ namespace magma {
 
     void recreateSwapchain()
     {
-      swapchain = magma::Swapchain<>(surface, device, physicalDevice, swapchain);
+      swapchain = magma::Swapchain<>(surface, device, physicalDevice, swapchain, vk::Extent2D{100, 100});
       device.waitIdle();
       auto const &swapchainImages(swapchain.getImages());
       swapchainUserData = SwapchainUserData(device, swapchain, userData, static_cast<uint32_t>(swapchainImages.size()));
```
It uses this branch:https://github.com/raven-os/magma/tree/swapchain_size which will hopefully soon be merged with https://github.com/raven-os/magma/pull/59

2018-06-06 08:34 UTC, Zeng-Zer reviewed
There're some complex constructor intializer lists.
It might be easier to read if you place them directly in the constructor block, i don't know if we'll lose some performance tho.

2018-06-06 08:34 UTC, Zeng-Zer commented on include/display/SuperCorbeau.hpp
> +    constexpr static char const *header_data =
Wtf :O ?

2018-06-06 08:34 UTC, Zeng-Zer commented on include/display/SpirvSource.hpp
> +#define SPIRV_SOURCE(NAME)						\
Comment this please :)

2018-06-06 08:34 UTC, Zeng-Zer commented on include/display/Display.hpp
> +	  , descriptorSetLayout(device.createDescriptorSetLayout({vk::DescriptorSetLayoutBinding{0, vk::DescriptorType::eCombinedImageSampler, 1, vk::ShaderStageFlagBits::eFragment, nullptr}}))
Do we have norm for line length ?

2018-06-06 08:34 UTC, Zeng-Zer commented on include/display/Display.hpp
> +	magma::Pipeline<> createPipeline(magma::Device<claws::no_delete> device, magma::Swapchain<claws::no_delete> swapchain, UserData const &userData)
Comments in this function would be appreciated

2018-06-06 08:34 UTC, davidzeng8 commented on include/display/Display.hpp
> +	    float priority[]{ 1.0 };
array of one element ?

2018-06-06 08:34 UTC, davidzeng8 commented on include/display/Display.hpp
> +	  magma::DynamicBuffer::RangeId tmpBuffer(stagingBuffer.allocate(display::superCorbeau::width * display::superCorbeau::height * 4));
Comments for this block would be appreciated

2018-06-06 08:34 UTC, davidzeng8 commented on include/display/Display.hpp
> +      void render()
Comments for this function would be appreciated

2018-06-06 19:31 UTC, Gaspard-- commented on include/display/WaylandSurface.hpp
> +    void shell_surface_ping(struct wl_shell_surface *shell_surface, uint32_t serial);
In this case i'd be against it: they are imitating the wayland api functions.

2018-06-06 19:32 UTC, Gaspard-- commented on source/listeners/KeyboardListener.cpp
> +    xkb_keysym_t keysym = xkb_state_key_get_one_sym(xkb_state, key + 8);
or introduce a constexpr variable @riamon-v

2018-06-06 19:33 UTC, Gaspard-- commented on include/display/SuperCorbeau.hpp
> +    constexpr static char const *header_data =
It's an image :P it's for easy testing purposes, it won't stay.

2018-06-06 19:34 UTC, Gaspard-- commented on include/display/SpirvSource.hpp
> +#define SPIRV_SOURCE(NAME)						\
Ahh, I didn't want to push this actually, but I guess I have to commit (pun intended) to it now.

2018-06-06 19:35 UTC, Gaspard-- commented on include/display/Display.hpp
> +	  , descriptorSetLayout(device.createDescriptorSetLayout({vk::DescriptorSetLayoutBinding{0, vk::DescriptorType::eCombinedImageSampler, 1, vk::ShaderStageFlagBits::eFragment, nullptr}}))
We don't IIRC, but I agree this is untidy.

2018-06-06 19:35 UTC, Gaspard-- commented on include/display/Display.hpp
> +	    float priority[]{ 1.0 };
Will change since apparently not self-evident.

2018-06-07 09:46 UTC, davidzeng8 commented on include/display/WaylandSurface.hpp
> +    void shell_surface_ping(struct wl_shell_surface *shell_surface, uint32_t serial);
Imo, it's better to stick with our coding style and we'll also call these functions with an object, `waylandSurface.shell_surface_ping()` vs `waylandSurface.shellSurfacePing()`

2018-06-07 17:54 UTC, riamon-v commented on include/display/WaylandSurface.hpp
> +    void shell_surface_ping(struct wl_shell_surface *shell_surface, uint32_t serial);
I agree let's go for this

2018-06-07 19:28 UTC, Zeng-Zer requested changes

2018-06-07 19:28 UTC, davidzeng8 commented on source/listeners/KeyboardListener.cpp
> +    if (utf32) {
bracket misplaced

2018-06-07 19:28 UTC, davidzeng8 commented on source/listeners/KeyboardListener.cpp
> +  char *keymap_string = static_cast<char *>(mmap(nullptr, size, PROT_READ, MAP_SHARED, fd, 0));
camelCase

2018-06-07 19:28 UTC, davidzeng8 commented on source/display/WaylandSurface.cpp
> +  void WaylandSurface::shellSurfaceConfigure(struct wl_shell_surface *shell_surface, uint32_t edges, int32_t width, int32_t height)
camelCase

2018-06-07 19:28 UTC, davidzeng8 commented on source/display/WaylandSurface.cpp
> +  void WaylandSurface::shellSurfacePing(struct wl_shell_surface *shell_surface, uint32_t serial)
camelCase

2018-06-07 19:28 UTC, davidzeng8 commented on include/listeners/KeyboardListener.hpp
> +    void keyboardModifiers(struct wl_keyboard *keyboard, uint32_t serial, uint32_t mods_depressed, uint32_t mods_latched, uint32_t mods_locked, uint32_t group);
camelCase

2018-06-07 19:28 UTC, davidzeng8 commented on include/display/WaylandSurface.hpp
> +    void shellSurfacePing(struct wl_shell_surface *shell_surface, uint32_t serial);
camelCase

2018-06-07 19:28 UTC, davidzeng8 commented on include/display/WaylandAdapters.hpp
> +    [](void *data, struct wl_shell_surface *shell_surface, uint32_t serial) {
camelCase

2018-06-07 19:28 UTC, davidzeng8 commented on include/display/WaylandAdapters.hpp
> +    [](void *data, struct wl_keyboard *keyboard, uint32_t serial, uint32_t mods_depressed, uint32_t mods_latched, uint32_t mods_locked, uint32_t group) {
camelCase

2018-06-07 19:28 UTC, davidzeng8 commented on include/listeners/PointerListener.hpp
> +  std::pair<double, double> pointerPosition;
I think it's better to have our own Position struct rather than std::pair.
std:;pair is generic but it makes it harder to understand.

2018-06-07 19:28 UTC, davidzeng8 commented on include/listeners/PointerListener.hpp
> +  std::pair<uint32_t, uint32_t> button;
same as above

2018-06-07 20:10 UTC, Zeng-Zer requested changes

2018-06-07 20:10 UTC, davidzeng8 commented on source/listeners/KeyboardListener.cpp
> +    if (utf32) {
bracket misplaced

2018-06-07 20:10 UTC, davidzeng8 commented on include/listeners/PointerListener.hpp
> +struct PointerPosition {
Imo it's better to put these structs under a new folder called "model"

2018-06-07 21:18 UTC, Gaspard-- commented on include/listeners/PointerListener.hpp
> +struct PointerPosition {
Hum, what bothers me is this isn't an `std::array` (ideally it would be a `claws::Vect` but claws doesn't have those yet)

2018-06-08 08:59 UTC, davidzeng8 commented on include/listeners/PointerListener.hpp
> +struct PointerPosition {
Same issue as before, it's harder to understand with generics.
Why does it bother you to not have an std::array here ?
(also bracket misplaced)

2018-06-08 11:05 UTC, Gaspard-- commented on include/listeners/PointerListener.hpp
> +struct PointerPosition {
Like I said on discord, nothing stops us from having a class that inherits from `std::array<double, 2u>` or just plain has it as a field. The advantage of std::array is that we can avoid violating the DRY principle (typically, when doing mathematical operations) by iterating on it's content.

2018-06-08 11:06 UTC, Gaspard-- commented on include/listeners/PointerListener.hpp
> +struct PointerPosition {
Also, std::array is far better than std::pair in this case: std::pair should be used when the left and right side tend to mismatch.

2018-06-08 11:08 UTC, Gaspard-- commented on include/listeners/PointerListener.hpp
> +struct PointerPosition {
I'm not really against the struct actually. I think we'll change it, if needed, later.

2018-06-09 14:23 UTC, Gaspard-- commented
As said in the commit above, to test the wayland subcompositor, please checkout magma to commit `3ddd11a42e4fecc0686489b8abbb12733894a3ee`. No more patch needed.

2018-06-09 17:23 UTC, Gaspard-- commented
And, now that commit is on magma's master, so no need to check out :D

2018-06-10 17:23 UTC, Zeng-Zer approved these changes

2018-06-10 20:04 UTC, merged